/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.memoryimprovementgame;
import java.io.*;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.*;


/**
 *
 * @author matt
 */
public class GameFrame extends javax.swing.JFrame {
    public static Clip clip;
    
    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnToMain = new javax.swing.JButton();
        relationGame = new javax.swing.JButton();
        nameGame = new javax.swing.JButton();
        relationAndNameGame = new javax.swing.JButton();
        everydayObjects = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        returnToMain.setText("Back");
        returnToMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnToMainActionPerformed(evt);
            }
        });

        relationGame.setText("Relation Game");
        relationGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationGameActionPerformed(evt);
            }
        });

        nameGame.setText("Name Game");
        nameGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameGameActionPerformed(evt);
            }
        });

        relationAndNameGame.setText("Relation and Name Game");
        relationAndNameGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relationAndNameGameActionPerformed(evt);
            }
        });

        everydayObjects.setText("Everyday Objects");
        everydayObjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                everydayObjectsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnToMain)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(relationAndNameGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(relationGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(everydayObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(178, 178, 178))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(relationGame)
                .addGap(35, 35, 35)
                .addComponent(nameGame)
                .addGap(36, 36, 36)
                .addComponent(relationAndNameGame)
                .addGap(34, 34, 34)
                .addComponent(everydayObjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(returnToMain)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnToMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnToMainActionPerformed
        MainMenuFrame mainFrame = new MainMenuFrame();
        mainFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnToMainActionPerformed

    private void relationGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationGameActionPerformed
        Game game = new Game();
        System.out.println("Starting game...");
        game.startGame();
        this.dispose();
    }//GEN-LAST:event_relationGameActionPerformed

    private void relationAndNameGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relationAndNameGameActionPerformed
        Game nameAndRelationGame = new Game();
        System.out.println("Starting game...");
        nameAndRelationGame.startNameAndRelationGame();
        this.dispose();
    }//GEN-LAST:event_relationAndNameGameActionPerformed

    private void nameGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameGameActionPerformed
        Game nameGame = new Game();
        System.out.println("Starting game...");
        nameGame.startNameGame();
        this.dispose();
    }//GEN-LAST:event_nameGameActionPerformed

    private void everydayObjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_everydayObjectsActionPerformed
        Game objGame = new Game();
        System.out.println("Starting game...");
        objGame.objectsGame();
        this.dispose();
    }//GEN-LAST:event_everydayObjectsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }
    
    public static void Sound() {
		try {
                    File file = new File("test.mp3");
                    AudioInputStream ais = AudioSystem.getAudioInputStream(GameFrame.class.getResource("/resources/" + file));
                    clip = AudioSystem.getClip();
                    clip.open(ais);
                    FloatControl gainControl = (FloatControl) clip.getControl(FloatControl.Type.MASTER_GAIN);
                    gainControl.setValue(-12.0f); //lowers the volume by 12db
                    clip.loop(clip.LOOP_CONTINUOUSLY);              	

		} 

                catch (Exception e) {
			e.printStackTrace();
		}
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton everydayObjects;
    private javax.swing.JButton nameGame;
    private javax.swing.JButton relationAndNameGame;
    private javax.swing.JButton relationGame;
    private javax.swing.JButton returnToMain;
    // End of variables declaration//GEN-END:variables
}
