package com.mycompany.memoryimprovementgame;

import java.io.File;
import javax.sound.sampled.AudioFormat;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author matt
 */
public class musicSelector extends javax.swing.JFrame {

    public static Clip audioClip;
    public boolean clipRunning = false;

    /**
     * Creates new form musicSelector
     */
    public musicSelector() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        sixtiesLbl = new javax.swing.JLabel();
        seventiesLbl = new javax.swing.JLabel();
        frankSinatra = new javax.swing.JButton();
        neilDiamond = new javax.swing.JButton();
        otisDayKnights = new javax.swing.JButton();
        beetles = new javax.swing.JButton();
        vanMorrison = new javax.swing.JButton();
        bobSeger = new javax.swing.JButton();
        lynyrdSkynyrd = new javax.swing.JButton();
        sisterSledge = new javax.swing.JButton();
        villagePeople = new javax.swing.JButton();
        ericClapton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backBtn.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        sixtiesLbl.setText("60s");

        seventiesLbl.setText("70s");

        frankSinatra.setText("The Way You Look Tonight - Frank Sinatra");
        frankSinatra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frankSinatraActionPerformed(evt);
            }
        });

        neilDiamond.setText("Sweet Caroline - Neil Diamond");
        neilDiamond.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                neilDiamondActionPerformed(evt);
            }
        });

        otisDayKnights.setText("Shout - Otis Day & The Knights");
        otisDayKnights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otisDayKnightsActionPerformed(evt);
            }
        });

        beetles.setText("Twist & Shout - Beetles");
        beetles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beetlesActionPerformed(evt);
            }
        });

        vanMorrison.setText("Brown Eyed Girl - Van Morrison");
        vanMorrison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vanMorrisonActionPerformed(evt);
            }
        });

        bobSeger.setText("Old Time Rock & Roll - Bob Seger");
        bobSeger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bobSegerActionPerformed(evt);
            }
        });

        lynyrdSkynyrd.setText("Sweet Home Alabama - Lynyrd Skynyrd");
        lynyrdSkynyrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lynyrdSkynyrdActionPerformed(evt);
            }
        });

        sisterSledge.setText("We Are Family - Sister Sledge");
        sisterSledge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisterSledgeActionPerformed(evt);
            }
        });

        villagePeople.setText("YMCA - Village People");
        villagePeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                villagePeopleActionPerformed(evt);
            }
        });

        ericClapton.setText("Wonderful Tonight - Eric Clapton");
        ericClapton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ericClaptonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(neilDiamond)
                            .addComponent(otisDayKnights)
                            .addComponent(beetles)
                            .addComponent(vanMorrison)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(sixtiesLbl))
                            .addComponent(frankSinatra))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lynyrdSkynyrd)
                                    .addComponent(sisterSledge)
                                    .addComponent(villagePeople)
                                    .addComponent(ericClapton)
                                    .addComponent(bobSeger))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 312, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(seventiesLbl)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sixtiesLbl)
                    .addComponent(seventiesLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(frankSinatra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(neilDiamond)
                        .addGap(2, 2, 2)
                        .addComponent(otisDayKnights)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(beetles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vanMorrison))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bobSeger)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lynyrdSkynyrd)
                        .addGap(2, 2, 2)
                        .addComponent(sisterSledge)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(villagePeople)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ericClapton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void frankSinatraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frankSinatraActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/60s/frankSinatra.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_frankSinatraActionPerformed

    private void neilDiamondActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_neilDiamondActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/60s/neilDiamond.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_neilDiamondActionPerformed

    private void otisDayKnightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otisDayKnightsActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/60s/otisDayKnights.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_otisDayKnightsActionPerformed

    private void beetlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beetlesActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/60s/beetles.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_beetlesActionPerformed

    private void vanMorrisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vanMorrisonActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/60s/vanMorrison.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_vanMorrisonActionPerformed

    private void bobSegerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bobSegerActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/70s/bobSeger.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bobSegerActionPerformed

    private void lynyrdSkynyrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lynyrdSkynyrdActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/70s/lynyrdSkynyrd.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lynyrdSkynyrdActionPerformed

    private void sisterSledgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisterSledgeActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/70s/sisterSledge.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_sisterSledgeActionPerformed

    private void villagePeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_villagePeopleActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/70s/villagePeople.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_villagePeopleActionPerformed

    private void ericClaptonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ericClaptonActionPerformed
        try {
            if (clipRunning) {
                audioClip.close();
            }
            String audioFilePath = "resources/70s/ericClapton.wav";
            File audioFile = new File(audioFilePath);
            AudioInputStream audioStream = AudioSystem.getAudioInputStream(audioFile);
            AudioFormat format = audioStream.getFormat();
            DataLine.Info info = new DataLine.Info(Clip.class, format);
            audioClip = (Clip) AudioSystem.getLine(info);
            audioClip.open(audioStream);
            audioClip.start();
            clipRunning = true;

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_ericClaptonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.dispose();
        //this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musicSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musicSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musicSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musicSelector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musicSelector().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton beetles;
    private javax.swing.JButton bobSeger;
    private javax.swing.JButton ericClapton;
    private javax.swing.JButton frankSinatra;
    private javax.swing.JButton lynyrdSkynyrd;
    private javax.swing.JButton neilDiamond;
    private javax.swing.JButton otisDayKnights;
    private javax.swing.JLabel seventiesLbl;
    private javax.swing.JButton sisterSledge;
    private javax.swing.JLabel sixtiesLbl;
    private javax.swing.JButton vanMorrison;
    private javax.swing.JButton villagePeople;
    // End of variables declaration//GEN-END:variables
}
